// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uppfinnaren_1_0_maxie1337.Models;

#nullable disable

namespace uppfinnaren_1_0_maxie1337.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("uppfinnaren_1_0_maxie1337.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Träprodukter",
                            Description = "Ett torn karvat in i ett träd.",
                            ImgUrl = "/Images/CTorn.jpg",
                            Name = "Torn"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Träprodukter",
                            Description = "Ett bord gjort utav en stubbe.",
                            ImgUrl = "/Images/Ctables.jpg",
                            Name = "Bord"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Träprodukter",
                            Description = "En konstig stol.",
                            ImgUrl = "/Images/Cchair.jpg",
                            Name = "Stol"
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Träprodukter",
                            Description = "En lurig tomte nu i juletider.",
                            ImgUrl = "/Images/CTomte.jpg",
                            Name = "Tomte"
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Keramik",
                            Description = "En vacker keramikvas.",
                            ImgUrl = "/Images/CVase.jpg",
                            Name = "Vas"
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Keramik",
                            Description = "En handgjord mugg av lera.",
                            ImgUrl = "/Images/CMug.jpg",
                            Name = "Mugg"
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Smycken",
                            Description = "Ett elegant halsband i silver.",
                            ImgUrl = "/Images/CNecklace.jpg",
                            Name = "Halsband"
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Smycken",
                            Description = "Ett armband med pärlor.",
                            ImgUrl = "/Images/CBracelet.jpg",
                            Name = "Armband"
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Konst",
                            Description = "En vacker tavla med landskap.",
                            ImgUrl = "/Images/CPainting.jpg",
                            Name = "Tavla"
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Konst",
                            Description = "En modern skulptur i sten.",
                            ImgUrl = "/Images/CStatue.jpg",
                            Name = "Skulptur"
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Inredning",
                            Description = "En retro bordslampa.",
                            ImgUrl = "/Images/CLamp.jpg",
                            Name = "Lampa"
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Inredning",
                            Description = "En handknuten matta.",
                            ImgUrl = "/Images/CRug.jpg",
                            Name = "Matta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
